### ISSUE TITLE
Implement ECHO command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#55]
Implement the ECHO command, which returns the message to the connection.
Reference: https://redis.io/docs/latest/commands/echo/

## Client-Server Spec:

Command File: ./internal/modules/connection/commands.go
Test File: ./internal/modules/connection/commands_test.go

Command: `echo`
Module: `constants.ConnectionModule`
Categories: `constants.ConnectionCategory`, `constants.FastCategory`
Description: `(ECHO message) Returns message.`
Sync: `false`

**Comment by dotslashbit** [comment]
I'm working on it
