### ISSUE TITLE
Implement RANDOMKEY command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#57]
Implement the RANDOMKEY command, which returns a random key from echovault (no database selection set yet).
Reference: https://redis.io/docs/latest/commands/randomkey/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `randomkey`
Module: `constants.GenericModule`
Categories: `constants.KeyspaceCategory`, `constants.ReadCategory`, `constants.SlowCategory`
Description: `(RANDOMKEY) Returns a random key.`
Sync: `false`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

NOTE: You may have to edit the `HandlerFuncParams` type to include a function that returns a random key.

**Comment by osteensco** [comment]
I'll take this one if that's ok
