### ISSUE TITLE
Implement RENAME command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#58]
Implement the RENAME command, which renames the specified key with the new name. 
Reference: https://redis.io/docs/latest/commands/rename/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `rename`
Module: `constants.GenericModule`
Categories: `constants.KeyspaceCategory`, `constants.WriteCategory`, `constants.SlowCategory`
Description: `(RENAME key newkey) Renames the specified key with the new provided name.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

NOTE: You may have to edit the `HandlerFuncParams` type to include a function that renames keys. Alternatively, you could use the `GetValues`, `DeleteKeys` and `SetValues` methods together to delete the old key and set a new key with the old value. The first approach would be more atomic, though.

At the moment, only replication clusters exist without sharding. So the key should be renamed across the entire cluster.

**Comment by dotslashbit** [comment]
working on it
