### ISSUE TITLE
Implement TYPE command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#61]
Implement the TYPE command, which returns the data type of the provided key.
Reference: https://redis.io/docs/latest/commands/type/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `type`
Module: `constants.GenericModule`
Categories: `constants.KeyspaceCategory`, `constants.ReadCategory`, `constants.FastCategory`
Description: `(TYPE key) Returns the string representation of the type of the value stored at key. The different types that can be returned are: string, integer, float, list, set, zset, hash and stream.`
Sync: `false`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by DMcP89** [comment]
@kelvinmwinuka  I'll pick this one up next

**Comment by kelvinmwinuka** [comment]
Thanks @DMcP89
