### ISSUE TITLE
Implement APPEND command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#62]
Implement the APPEND command, which appends the provided string to the value at the specified key if the value is a string.
Reference: https://redis.io/docs/latest/commands/append/

## Client-Server Spec:

Command File: ./internal/modules/string/commands.go
Test File: ./internal/modules/string/commands_test.go

Command: `append`
Module: `constants.StringModule`
Categories: `constants.StringCategory`, `constants.WriteCategory`, `constants.FastCategory`
Description: `(APPEND key value) If key already exists and is a string, this command appends the value at the end of the string. If key does not exist it is created and set as an empty string, so APPEND will be similar to [SET] in this special case.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_string.go
Test File: ./echovault/api_string_test.go

**Comment by DMcP89** [comment]
@kelvinmwinuka I'll pick this one up
