### ISSUE TITLE
Implement DECR command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#63]
Implement the DECR command, which decrements the value at the specified key by 1 if the value is an integer or a float.
Reference: https://redis.io/docs/latest/commands/decr/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `decr`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(DECR key) Decrements the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation. An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by dotslashbit** [comment]
working on it
