### ISSUE TITLE
Implement DECRBY command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#64]
Implement the DECRBY command, which decrements the value at the specified key by the specified amount if the value is an integer or a float.
Reference: https://redis.io/docs/latest/commands/decrby/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `decrby`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(DECRBY key decrement) The DECRBY command reduces the value stored at the specified key by the specified decrement. If the key does not exist, it is initialized with a value of 0 before performing the operation. If the key's value is not of the correct type or cannot be represented as an integer, an error is returned.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by dotslashbit** [comment]
working on it
