### ISSUE TITLE
Implement INCRBY command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#65]
Implement the INCRBY command, which increments the value at the specified key by the specified amount if the value is an integer or a float.
Reference: https://redis.io/docs/latest/commands/incrby/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `incrby`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(INCRBY key increment) Increments the number stored at key by increment. If the key does not exist, it is set to 0 before performing the operation. An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by dotslashbit** [comment]
working on it
