### ISSUE TITLE
Implement INCRBYFLOAT command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#67]
Implement the INCRBYFLOAT command, which increments the value at the specified key by the specified float amount if the value is an integer or a float.
Reference: https://redis.io/docs/latest/commands/incrbyfloat/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `incrbyfloat`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(INCRBYFLOAT key decrement) Increment the string representing a floating point number stored at key by the specified increment. By using a negative increment value, the result is that the value stored at the key is decremented (by the obvious properties of addition). If the key does not exist, it is set to 0 before performing the operation.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by dotslashbit** [comment]
working on it
