### ISSUE TITLE
Implement GETDEL command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#68]
Implement the GETDEL command, which gets the current value at the specified key and then delete the key.
Reference: https://redis.io/docs/latest/commands/getdel/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `getdel`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(GETDEL key) Get the value of key and delete the key. This command is similar to [GET](https://redis.io/docs/latest/commands/get/), except for the fact that it also deletes the key on success (if and only if the key's value type is a string).`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by osteensco** [comment]
@kelvinmwinuka I'll grab this one next
