### ISSUE TITLE
Implement GETEX command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#69]
Implement the GETEX command, which gets the current value at the specified key and then sets an expiry for the key.
Reference: https://redis.io/docs/latest/commands/getex/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `getex`
Module: `constants.GenericModule`
Categories:  `constants.WriteCategory`, `constants.FastCategory`
Description: `(GETEX key [EX seconds | PX milliseconds | EXAT unix-time-seconds |
  PXAT unix-time-milliseconds | PERSIST]) Get the value of key and optionally set its expiration. GETEX is similar to [GET], but is a write command with additional options.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

**Comment by osteensco** [comment]
@kelvinmwinuka I'll pick this one up next after my current PR gets approved and I address anything that needs fixing there.
