### ISSUE TITLE
Implement HMGET command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/EchoVault#70]
Implement the HMGET command, which gets the values of multiple fields from a hash.
Reference: https://redis.io/docs/latest/commands/hmget/

## Client-Server Spec:

Command File: ./internal/modules/hash/commands.go
Test File: ./internal/modules/hash/commands_test.go

Command: `hmget`
Module: `constants.HashModule`
Categories:  `contants.HashCategory`, `constants.ReadCategory`, `constants.FastCategory`
Description: `(HMGET key field [field ...]) Returns the values associated with the specified fields in the hash stored at key.`
Sync: `false`

## Embedded Spec:

Command File: ./echovault/api_hash.go
Test File: ./echovault/api_hash_test.go

**Comment by thesambayo** [comment]
@kelvinmwinuka I'm picking this as my first issue🙏🏽
