### ISSUE TITLE
Server panics when connecting with `redis-cli`

### ISSUE THREAD

**Issue by bduffany** [EchoVault/EchoVault#71]
Hello, I am trying out this project because it looks cool and I'd like to learn more about Raft. If you're open to it, I might be interested in implementing some of the Redis commands that aren't yet supported, as a way to learn :)

When running the hello world server (from the README) and connecting with `redis-cli`, the server panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbd1982]

goroutine 10 [running]:
github.com/echovault/echovault/echovault.(*EchoVault).handleCommand(0xc000181b88, {0xde2418, 0xc0001fc5d0}, {0xc0002c6000, 0x11, 0x2000}, 0xc000025610, 0x0, 0x0)
        /home/b/go/pkg/mod/github.com/echovault/echovault@v0.6.0/echovault/modules.go:110 +0x702
github.com/echovault/echovault/echovault.(*EchoVault).handleConnection(0xc000181b88, {0xde5dd0, 0xc0000a4500})
        /home/b/go/pkg/mod/github.com/echovault/echovault@v0.6.0/echovault/echovault.go:445 +0x2c8
created by github.com/echovault/echovault/echovault.(*EchoVault).startTCP in goroutine 1
        /home/b/go/pkg/mod/github.com/echovault/echovault@v0.6.0/echovault/echovault.go:415 +0x605
```

I think this is a bug because `redis-cli` should be using RESP, and the README says that echovault is RESP-compatible?

Server code:

```
func main() {
	server, err := echovault.NewEchoVault() // echovault.WithConfig(cfg))
	if err != nil {
		log.Fatal(err)
	}
	server.Start()
}
```

The same error happens if I run the included CLI with `echovault -data-dir /tmp/echovault -bind-addr 127.0.0.1`

**Comment by kelvinmwinuka** [comment]
Hi @bduffany 

Thanks for reporting this bug. If you want to take a crack at this, let me know. Otherwise, will look into this and create a fix. 

If you'd like to work on adding some commands that are currently unsupported, check out the other issues here, or create an issue for the command you wish to implement :)

**Comment by kelvinmwinuka** [comment]
I am closing this issue as the latest release (v0.7.0) addresses this problem. If the issue persists, we can re-open it.
