### ISSUE TITLE
Server requires root

### ISSUE THREAD

**Issue by bduffany** [EchoVault/EchoVault#72]
I tried running the server in the `cmd/` directory, but got this error: `2024/06/15 22:47:03 new preamble store -> mkdir error: mkdir /var/lib/echovault: permission denied`

Maybe the `/var/lib/echovault` dir should default to `~/.local/lib/echovault` when not running as root?

**Comment by kelvinmwinuka** [comment]
Would you like to submit a PR to correct this? If not, I will submit a fix and update this issue.

**Comment by kelvinmwinuka** [comment]
Update - There was a recent merge that changed the default data-dir to the current working directory by default. 

I think this should solve this particular issue. I will test it after the next release tomorrow.
