### ISSUE TITLE
go get produces incorrect go module path

### ISSUE THREAD

**Issue by brandonrjacobs** [EchoVault/EchoVault#88]
Seems as your go module name is lowercased so in your ReadMe downloading via `go get...` returns this error. 
```
go: github.com/echoVault/echoVault@latest (v0.8.0) requires github.com/echoVault/echoVault@v0.8.0: parsing go.mod:
        module declares its path as: github.com/echovault/echovault
                but was required as: github.com/echoVault/echoVault
```

**Comment by kelvinmwinuka** [comment]
Thanks for pointing this out @brandonrjacobs,

This is has been fixed by this [#89](https://github.com/EchoVault/EchoVault/pull/89)
